FROM jupyter/base-notebook

RUN python -m pip install python-telegram-bot

RUN python -m pip install octave_kernel
    
USER root

RUN apt-get -y update \
 && apt-get -y install \
    libcurl4-openssl-dev \
    gnuplot octave liboctave-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

ADD bot.py Listener.py callbacks.py config.py /home/jovyan/

WORKDIR /home/jovyan

USER $NB_UID
